"""Initial migration.

Revision ID: 83f43077a61c
Revises: 
Create Date: 2020-07-27 15:27:21.318463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f43077a61c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('client_email', sa.String(length=100), nullable=False))
    op.add_column('project', sa.Column('client_name', sa.String(length=100), nullable=False))
    op.add_column('project', sa.Column('client_phone', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('max_members', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('project_desc', sa.Text(), nullable=False))
    op.add_column('project', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('project_name', sa.String(length=100), nullable=False))
    op.add_column('project', sa.Column('project_stack', sa.String(length=100), nullable=False))
    op.add_column('project', sa.Column('project_status', sa.String(length=100), nullable=False))
    op.drop_column('project', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('project', 'project_status')
    op.drop_column('project', 'project_stack')
    op.drop_column('project', 'project_name')
    op.drop_column('project', 'project_id')
    op.drop_column('project', 'project_desc')
    op.drop_column('project', 'max_members')
    op.drop_column('project', 'client_phone')
    op.drop_column('project', 'client_name')
    op.drop_column('project', 'client_email')
    # ### end Alembic commands ###
